"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['setapp_disconnect.py']
APP_NAME = "SetappDisconnect"
DATA_FILES = []
OPTIONS = {
    'iconfile': 'SetappDisconnectIcon.icns',
    'plist': {
            'CFBundleName': APP_NAME,
            'CFBundleDisplayName': APP_NAME,
            'CFBundleGetInfoString': "Logout from Setapp",
            'CFBundleIdentifier': "",
            'CFBundleVersion': "0.0.1",
            'CFBundleShortVersionString': "0.0.1",
            'NSHumanReadableCopyright': u"Copyright © 2019, Marco Loew, All Rights Reserved"
    }
}

setup(
    app=APP,
    name=APP_NAME,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
